waxb/add network tag
mineiros-io/terraform-google-gke-autopilot-cluster pull request #6
Opened 2022-09-14 14:47 UTC by waxb

- feat!: support for `node_pool_auto_config` added
- chore: changelog updated
- chore: tests updated

2022-09-14 15:13 UTC, mariux commented on CHANGELOG.md
> +- BREAKING: Upgraded provider to `~> 4.34` to add support for `node_pool_auto_config`
not a breaking change as it is just a minor update...

2022-09-14 15:13 UTC, mariux commented on versions.tf
> +  required_version = ">= 1.0, < 2.0"
```suggestion
  required_version = "~> 1.0"
```

2022-09-14 15:14 UTC, mariux commented on versions.tf
> +    }
why do we need both providers?

2022-09-14 15:17 UTC, mariux commented on README.tfdoc.hcl
> +          (Optional) Node pool configs that apply to auto-provisioned node pools
```suggestion
          Node pool configs that apply to auto-provisioned node pools
```

2022-09-14 15:17 UTC, waxb commented on CHANGELOG.md
> +- BREAKING: Upgraded provider to `~> 4.34` to add support for `node_pool_auto_config`
based on a previous release in this module i thought this falls under the same category as it introduces a bigger minimum provider version requirement
> BREAKING: Upgrade provider to `~4.16` to add support for `authenticator_groups_config`

i can remove

2022-09-14 15:22 UTC, waxb commented on versions.tf
> +    }
i'm still not fully familiar with our module writing tidbits yet (constantly learning and working on it! :) ) so i'm always trying to make assumptions based on other modules we have, for example this (where we use `google-beta` also):
https://github.com/mineiros-io/terraform-google-github-workload-identity/blob/main/versions.tf

2022-09-14 15:22 UTC, waxb commented on CHANGELOG.md
> +- BREAKING: Upgraded provider to `~> 4.34` to add support for `node_pool_auto_config`
as mentioned, i'm trying to work on assumptions on previous work you've introduced as a team

2022-09-14 15:25 UTC, mariux commented on main.tf
> +        }
please see https://www.notion.so/Creating-new-Mineiros-Modules-e26d711cda7d43f39fe73d316eaf0d6e#d6f4820e6bd14c61bad85da5f3068cd3

```suggestion
    for_each = var.node_pool_auto_config != null ? [var.node_pool_auto_config] : []

    content {
      dynamic "network_tags" {
        for_each = try([node_pool_auto_config.value.network_tags], [])

        content {
          tags = try(network_tags.value.tags, null)
        }
```

2022-09-14 15:26 UTC, mariux commented on README.tfdoc.hcl
> +        type        = any
please never reference `any` in docs... 

```suggestion
        type        = object(node_pool_auto_config)
```

2022-09-14 15:27 UTC, mariux commented on README.tfdoc.hcl
> +          type        = any
```suggestion
          type        = object(network_tags)
```

2022-09-14 15:28 UTC, mariux commented on CHANGELOG.md
> +- BREAKING: Upgraded provider to `~> 4.34` to add support for `node_pool_auto_config`
it's only breaking if support for a previous major released is removed.

that's why it is a minor release in the provider ;)

2022-09-14 15:30 UTC, waxb commented on CHANGELOG.md
> +- BREAKING: Upgraded provider to `~> 4.34` to add support for `node_pool_auto_config`
i know, but then this wasn't a breaking change either? it was just a 4.10 -> 4.16

2022-09-14 16:03 UTC, zied-elouaer submitted a review, later dismissed
LGTM

2022-09-14 16:19 UTC, mariux requested changes

2022-09-14 16:19 UTC, mariux commented on CHANGELOG.md
> +- Upgrade provider to `~4.16` to add support for `authenticator_groups_config`
```suggestion
- Upgrade provider to `~> 4.16` to add support for `authenticator_groups_config`
```

2022-09-14 16:19 UTC, mariux commented on main.tf
>    project = local.project
please drop local project loading... the provider is falling back automatically..

2022-09-14 16:19 UTC, mariux commented on CHANGELOG.md
> +- Upgraded provider to `~> 4.34` to add support for `node_pool_auto_config`
missed we really actually change to `google-beta` provider here.. not really breaking but people need to configure and pin this provider now when using the module.. so maybe BREAKING again? ;) sorry for the confusion but the message is also missing the change here ;)

2022-09-14 16:19 UTC, mariux commented on test/terramate_google.tm.hcl
> +        }
we are not using google provider here but beta

2022-09-14 17:33 UTC, mariux requested changes

2022-09-14 17:33 UTC, mariux commented on CHANGELOG.md
> +- Upgrade provider to `~4.16` to add support for `authenticator_groups_config`
```suggestion
- Upgrade provider to `~> 4.16` to add support for `authenticator_groups_config`
```

2022-09-15 08:37 UTC, zied-elouaer submitted a review, later dismissed

2022-09-15 16:04 UTC, zied-elouaer approved these changes, later dismissed

2022-09-15 17:38 UTC, mariux requested changes

2022-09-15 17:38 UTC, mariux commented on CHANGELOG.md
> +- BREAKING: Upgraded provider to `~> 4.34` to and switched to `beta` for adding support for `node_pool_auto_config`
```suggestion
- BREAKING: Upgraded provider to `~> 4.34` to and switched to `google-beta` Terraform Provider for adding support for `node_pool_auto_config`
```

2022-09-15 17:38 UTC, mariux commented on test/terramate_google.tm.hcl
> +          source  = "hashicorp/google-beta"
```suggestion
          source  = "hashicorp/google"
```

2022-09-15 17:38 UTC, mariux commented on test/terramate_google.tm.hcl
> +          source  = "hashicorp/google-beta"
lets update from latest template again should be fine then

2022-09-16 08:29 UTC, soerenmartius approved these changes, later dismissed
lgtm! good job @waxb

2022-09-16 08:45 UTC, mariux commented on README.md
> +and is compatible with the Terraform Google Provider Beta version ~> 4.34**
we should think about how to communicate the stuff we discussed yesterday about beta and non beta setups...(just a note)

2022-09-16 08:47 UTC, mariux requested changes

2022-09-16 08:47 UTC, mariux commented on main.tf
> +  provider = google-beta
```suggestion
  provider = google-beta
  
  project = var.project
```

2022-09-16 12:01 UTC, soerenmartius approved these changes
lgtm

2022-09-19 08:50 UTC, mariux approved these changes
lgtm

2022-09-19 09:09 UTC, zied-elouaer approved these changes

2022-09-19 09:10 UTC, waxb commented
thank you very much for your thorough reviews

2022-09-19 09:11 UTC, merged